# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/healthcare
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# ===============================
# SWAGGER
# ===============================
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
assignment.upload.path=uploads/